name: Build TOTK Explorer v3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Switch OVL
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install libtesla
        run: |
          git clone --depth 1 https://github.com/WerWolv/libtesla.git /tmp/libtesla
          cd /tmp/libtesla
          make install

      - name: Build
        run: |
          make -j2

      - name: Prepare artifact
        run: |
          mkdir -p artifact/sd/switch/.overlays
          cp *.ovl artifact/sd/switch/.overlays/

          if [ -f data/points.csv ]; then
            mkdir -p artifact/sd/switch/totk_explorer
            cp data/points.csv artifact/sd/switch/totk_explorer/
          fi

      - name: Upload OVL
        uses: actions/upload-artifact@v4
        with:
          name: TOTK-Explorer-v3
          path: artifact/
          if-no-files-found: error
